### ISSUE TITLE
cells.Tabs fails when tab labels are Subscribed cells

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/object_database#58]
Take a look at my new `cells_demo/tabs.py` tests in the branch `alex-cells-tabs-bug`. The simple case works as expected, but simply wrapping the titles of the tabs in `Subscribed` cells makes it impossible to click on the 2nd tab and see its contents.

Pasting the code of that test below for self-containedness:
```python
class TwoSubscribedTabs(CellsTestPage):
    def cell(self):
        return cells.Tabs(
            [
                (cells.Subscribed(lambda: "Tab1"), "Tab1 Text"),
                (cells.Subscribed(lambda: "Tab2"), "Tab2 Text"),
            ]
        )

    def text(self):
        return "Two tabs with text"
```

**Comment by atzannes** [comment]
@darth-cheney @dkrasner this used to work and is now broken :) The reason to have that be a subscribed cell is that we want the text to update based on some metric computed from the ODB, (e.g., how many object of some type there are in ODB, and the tab displays info about those objects).

**Comment by darth-cheney** [comment]
@atzannes I'm getting the following error stack:
```
Traceback (most recent call last):
  File "/home/ecgade/projects/braxton/12-3/object_database/object_database/web/cells/cells.py", line 2006, in recalculate
    newCell = Cell.makeCell(self.cellFactory())
  File "<string>", line 5, in <lambda>
TypeError: Type 'tabs.TabsSchema.Tab1Item' has not had any fields defined yet
```
This original error prevents the given Cell from being prepared for reuse, which then triggers another error about it already having a set parent.
  
That said, I'm not 100% sure how the schemas specified in the example are supposed to work. Any ideas?
