### ISSUE TITLE
cells.Popover doesn't let me select text on the Popover window

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/object_database#74]
I am using the Popover to display a cell that may potentially contain a lot of text in an abbreviated way in a Table. When I click on the cell with the abbreviated info, the Popover overlays a window with the full contents of the cell. This works as expected, so far. 

However, when I try to select text from the overlay window of the Popover (in order to copy it and work on it somewhere else), the overlay window disappears before I am able to grab the text. It would be good to not remove the popover window when we click on top of it.

**Comment by darth-cheney** [comment]
@atzannes If it's not too much work, do you mind pushing a small CellsDemoPage example that demonstrates the problem?

**Comment by atzannes** [comment]
@darth-cheney  sure thing,
I added an example in branch [alex-issue74-example](https://github.com/APrioriInvestments/object_database/tree/alex-issue74-example)

**Comment by darth-cheney** [comment]
@atzannes See if #78 does the trick

**Comment by darth-cheney** [comment]
Cloed by #78
