### ISSUE TITLE
cells.Table displays wrong item number in multi-page layout

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/object_database#75]
Say we have a Table with 200 rows and 50 rows per page. No matter what page we're on, the first column will be an item number from 1 to 50, regardless of the page on which we are.

**Comment by darth-cheney** [comment]
@atzannes This is known from #17 and was addressed in #50. That PR is pretty stale at this point, however, and I need to see if I can rebase it and pull it in again. The idea was that I would write some automated end to end tests when I did this, but first we need to get the new test PR (#72) incorporated.

**Comment by atzannes** [comment]
Duplicate of #17
