### ISSUE TITLE
cells.Text(0) blows up at the javascript layer

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/object_database#80]
Not only should we be preventing this from being a problem on the server side by converting the argument to a string, we should also fix the bug where this bad data causes the maquette rendering to throw an exception, which causes the entire page to become unresponsive.

**Comment by darth-cheney** [comment]
@braxtonmckee Check out the [eric-issue-80](https://github.com/APrioriInvestments/object_database/tree/eric-issue-80) branch, which has a quick fix to this. I can file a PR if you want too, but I think this can be merged in safely.

**Comment by darth-cheney** [comment]
@braxtonmckee has this been merged in or should I file aPR?

**Comment by braxtonmckee** [comment]
Not merged yet

**Comment by darth-cheney** [comment]
Closed by #89
