### ISSUE TITLE
popovers that disappear from the dom while the popover is open never go away

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/object_database#87]
if you have a popover and you open it and then the cell that contained its root gets removed, we're not removing the open popover, and it gets orphaned. This really only happens if the data is getting updated on the _server_ side.  To repro, add a popover associated with the "happy service" in the services test page, and you should be able to see it oscillating. maybe we need to think about how to test server-driven updates a little better...

**Comment by darth-cheney** [comment]
Looking into this now. I don't think the server updates are really the problem, but rather that we are using the Bootstrap library for popovers and it actually keeps the popover dom elements in a different place than our component structure. One option would be to write our own popover setup but that's probably an unnecessary amount of work -- I can find the best place to hook in and ensure that all orphaned popovers go away.

**Comment by darth-cheney** [comment]
Closed by #90
